// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bowdewdgborotukabwbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvd2Rld2RnYm9yb3R1a2Fid2JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyOTIxOTEsImV4cCI6MjA1NDg2ODE5MX0.GeKCydZGpTJXoCgRJBews_3t0_bYuiOA4rOujLKUXGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);